dist: jammy
group: dev
services:
  - postgresql
script: 
  - systemctl status postgresql
  - systemctl status postgresql@-main
  - journalctl -u postgresql
  - psql -c 'SELECT version();' -U postgres

